### ISSUE TITLE
Make artoolkit.api.js node.js compliant and remove references to DOM object in typescript version and javascript

### ISSUE THREAD

**Issue by kalwalt** [webarkit/jsartoolkitNFT#128]
There few key points to solve to make artoolkitNFT.api.js (to be precise the libs compiled with artoolkitNFT.api.js -> artoolkitNFT_wasm.js and artoolkitNFT.min.js) to use on node.js. At the moment it can not be used because there are DOM objects and `self` is not recognized as globalThis:
https://github.com/webarkit/jsartoolkitNFT/blob/5a3230c8940613958e0cd8c13c9d5a858a03a33b/js/artoolkitNFT.api.js#L4-L9
self is accepted in a worker env but not under NODE.
I think that code should add a conditional with `scope = global` for the NODE env.
Plus we need to remove all references to canvas or document objects. We don't need them because we pass imageData. This is also applicable to the Typescript version and need a rewrite in this sense.

**Comment by kalwalt** [comment]
Inside **artoolkitNFT.api.js** and **ARControllerNFT.ts** will try to remove canvas, ctx, image, options, and orientation properties from ARControllerNFT class. Maybe i can remove other part of the code.

**Comment by kalwalt** [comment]
> Inside **artoolkitNFT.api.js** and **ARControllerNFT.ts** will try to remove canvas, ctx, image, options, and orientation properties from ARControllerNFT class. Maybe i can remove other part of the code.

This is not enough, the lib will fail while loading the camera or other resources because it is based on XMLHttpRequest that is not supported on a Node.js environment. It's needed to change the ajax function to another that use `FS.readFile()`, we have already FS thanks to Emscripten, so it shouldn't be too difficult...

**Comment by kalwalt** [comment]
You can do this simple test, given this code:
```js
var Module = require('../build/artoolkitNFT_wasm.js')

Module.onRuntimeInitialized = async function(){
 
    var ar = new ARControllerNFT(640, 480, '../examples/Data/camera_para.dat');
 
}
```


You will get this error:
```
ReferenceError: XMLHttpRequest is not defined
    at ajax (/home/walter/kalwalt-github/webarkit-org/jsartoolkitNFT/build/artoolkitNFT_wasm.js:1:12857)
    at Object.loadCamera (/home/walter/kalwalt-github/webarkit-org/jsartoolkitNFT/build/artoolkitNFT_wasm.js:1:12412)
    at ARCameraParamNFT.load (/home/walter/kalwalt-github/webarkit-org/jsartoolkitNFT/build/artoolkitNFT_wasm.js:1:9344)
    at new ARCameraParamNFT (/home/walter/kalwalt-github/webarkit-org/jsartoolkitNFT/build/artoolkitNFT_wasm.js:1:9043)
    at new ARControllerNFT (/home/walter/kalwalt-github/webarkit-org/jsartoolkitNFT/build/artoolkitNFT_wasm.js:1:828)
    at Object.Module.onRuntimeInitialized (/home/walter/kalwalt-github/webarkit-org/jsartoolkitNFT/tests/test2.js:7:14)
    at doRun (/home/walter/kalwalt-github/webarkit-org/jsartoolkitNFT/build/artoolkitNFT_wasm.js:1:781091)
    at run (/home/walter/kalwalt-github/webarkit-org/jsartoolkitNFT/build/artoolkitNFT_wasm.js:1:781251)
    at runCaller (/home/walter/kalwalt-github/webarkit-org/jsartoolkitNFT/build/artoolkitNFT_wasm.js:1:780759)
    at removeRunDependency (/home/walter/kalwalt-github/webarkit-org/jsartoolkitNFT/build/artoolkitNFT_wasm.js:1:23840)


```

**Comment by kalwalt** [comment]
Note that also the dist lib ARToolkitNFT.js will fails under node.js with a similar error.

**Comment by kalwalt** [comment]
We should build the dist lib with these instructions https://github.com/axios/axios/issues/456#issuecomment-285287911

**Comment by kalwalt** [comment]
Solved in #140
