### ISSUE TITLE
error with WebAssembly, failing to load example

### ISSUE THREAD

**Issue by kalwalt** [webarkit/jsartoolkitNFT#97]
With my Android Oppo A72 i got this error running the ES6 example:
`failed to asynchronously prepare wasm: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory (anonymous)	@	artoolkitNFT_ES6_wasm.js:9 artoolkitNFT_ES6_wasm.js:9 RangeError: WebAssembly.instantiate(): Out of memory: wasm memory artoolkitNFT_ES6_wasm.js:9 Uncaught (in promise) RuntimeError: abort(RangeError: WebAssembly.instantiate(): Out of memory: wasm memory). Build with -s ASSERTIONS=1 for more info.     at abort (https://kalwalt.github.io/kalwalt-interactivity-AR/resources/ARToolkitNFT.js:35:11612)     at https://kalwalt.github.io/kalwalt-interactivity-AR/resources/ARToolkitNFT.js:35:650135 ﻿`
and the example stop to load any resources.

**Comment by kalwalt** [comment]
fixed with commit https://github.com/webarkit/jsartoolkitNFT/commit/2debddaf0dbdafd950d6ebb9476be17bb4e7423d  changes are in master now.
